### ISSUE TITLE
svmlib Binary file

### ISSUE THREAD

**Issue by nahidq** [dsoellinger/blind_image_quality_toolbox#1] opened 2020-06-17 04:26 UTC
Thanks for providing this code.  I tried to run this code but I got this error:
'svm-scale' is not recognized as an internal or external command, 
operable program or batch file.
'svm-predict' is not recognized as an internal or external command, 
operable program or batch file. 
It seems that these two binary file do not work. I also rename svm-scale.exe1 to svm-ecale.exe, but the peoblem was not solved.

**Comment by dsoellinger** [comment] 2020-06-27 14:44
Thanks for pointing that out. I guess you are trying to run Brisque?

This issue is caused by the libsvm path mistakenly being hardcoded in these two lines: 
https://github.com/dsoellinger/blind_image_quality_toolbox/blob/274454d91e4d41b5aa4c801341e693da5ce0c139/%2Bbrisque/brisquescore.m#L37-L38

It can be fixed by replacing:
`/usr/local/Cellar/libsvm/3.22/bin/svm-scale` with `svm-scale`
`/usr/local/Cellar/libsvm/3.22/bin/svm-predict` with `svm-predict`


**Note:**
You might also have add the right version (try 3.22) of libsvm to the path before running Brisque. See https://github.com/dsoellinger/blind_image_quality_toolbox/blob/274454d91e4d41b5aa4c801341e693da5ce0c139/computeQualityMetrics.m#L23

**Closed as completed** 2020-06-28 11:36 UTC

**Comment by nahidq** [comment] 2020-06-29 04:59
Thanks for your reply. My problem was solved.

Best regards,
Nahid
